[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.zip', 'php82Extensions.gd', 'php82Extensions.fileinfo', 'php82Extensions.tokenizer', 'php82Packages.composer', 'nodejs-18_x']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist || true',
  'composer require cloudinary-labs/cloudinary-laravel:^2.0 --no-interaction --no-progress -W',
  'npm ci --legacy-peer-deps'
]

[phases.build]
cmds = [
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan config:clear && php artisan migrate --force && rm -rf public/storage && php artisan storage:link --force && php artisan serve --host=0.0.0.0 --port=$PORT'

