# Simple Nixpacks configuration for Laravel + Inertia.js + React
# Use this if nixpacks.toml doesn't work

[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.pdo',
  'php82Extensions.pdo_mysql',
  'php82Extensions.mbstring',
  'php82Extensions.xml',
  'php82Extensions.curl',
  'php82Extensions.zip',
  'php82Extensions.gd',
  'php82Extensions.tokenizer',
  'php82Extensions.fileinfo',
  'php82Extensions.bcmath',
  'php82Packages.composer',
  'nodejs_20'
]

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-scripts',
  'npm ci --omit=dev'
]

[phases.build]
cmds = [
  'npm run build',
  'php artisan optimize:clear',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

